AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test CloudFormation
Parameters:
  IAMRole:
    Type: String
    Default: 'arn:aws:iam::345814638087:role/IAM-LAMBDA-SERVICE'
Resources:
  cflambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: thisistestlambdafunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: 'arn:aws:iam::345814638087:role/IAM-LAMBDA-SERVICE'
      Code:
        S3Bucket: 's3-ftp-source'
        S3Key:  'code/thisistestlambdafunction.zip'
      MemorySize: 10240
      Timeout: 900
      Description: Default Lambda