AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test CloudFormation
Parameters:
  IAMRole:
    Type: String
    Default: 'arn:aws:iam::345814638087:role/IAM-LAMBDA-SERVICE'
Resources:
  cflambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: thisistestlambdafunction
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: 'arn:aws:iam::345814638087:role/IAM-LAMBDA-SERVICE'
      Code:
        S3Bucket: 's3-ftp-source'
        S3Key:  'code/thisistestlambdafunction.zip'
      MemorySize: 10240
      Timeout: 300
      Description: Default Lambda
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "ETL_Test"
      Role: 'arn:aws:iam::345814638087:role/IAM-GLUE-SERVICE'
      Command:
        Name: glueetl
        PythonVersion:  '3'
        ScriptLocation:
          Fn::Sub:  's3://s3-ftp-source/code/code.py'
      GlueVersion:  '2.0'
      WorkerType: 'Standard'
      NumberOfWorkers:  2
      ExecutionProperty:
        MaxConcurrentRuns:  24